[package]
name = "cmd-rs"
version = "0.1.0"
authors = ["dimos <doubledimos@outlook.com>"]
edition = "2018"

[dependencies.cmd-command]
path = "crates/cmd-command"

[dependencies.cmd-core]
path = "crates/cmd-core"

[dependencies.cmd-option]
path = "crates/cmd-option"